pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Build stage'
            }
        }
            stage('Test') {
            steps {
                echo 'Test stage'
            }
            }
            stage('Deploy') {
            steps {
                echo 'Deploy stage'
            }
            }
    }
	
	post {
	
	
	always {
	emailext body: 'Test mail', subject: 'Pipeline report', to: 'akshay.learn2021@gmail.com'
	}
	}
}
